version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: connect-aid-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backEnd:/app
      - /app/node_modules
      - ./backEnd/uploads:/app/uploads
    networks:
      - connect-aid-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/test"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Frontend service
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: connect-aid-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - connect-aid-network

networks:
  connect-aid-network:
    driver: bridge
