version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: connect-aid-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backEnd/.env
    volumes:
      - ./backEnd:/app
      - /app/node_modules
      - ./backEnd/uploads:/app/uploads
    networks:
      - connect-aid-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "--tries=1", "http://localhost:5000/api/health" , "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Frontend service
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: connect-aid-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - connect-aid-network

networks:
  connect-aid-network:
    driver: bridge
