version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: connect-aid-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backEnd/.env
    volumes:
      - ./backEnd:/app
      - /app/node_modules
      - ./backEnd/uploads:/app/uploads
    networks:
      - connect-aid-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000/test"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s

  # Frontend service
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: connect-aid-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      # Replace YOUR_EC2_PUBLIC_IP with your actual EC2 public IP or domain name
      - VITE_API_URL=http://52.201.237.207:5000
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - connect-aid-network

networks:
  connect-aid-network:
    driver: bridge
